# Generated by Django 5.2 on 2025-07-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libraryuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/profile_photo.png', null=True, upload_to='profile_photos/'),
        ),
    ]
